ALTER TABLE usuarios AUTO_INCREMENT = 1;
ALTER TABLE fornecedores AUTO_INCREMENT = 1;
ALTER TABLE medicamentos AUTO_INCREMENT = 1;
ALTER TABLE movimentacoes AUTO_INCREMENT = 1;
ALTER TABLE alertas AUTO_INCREMENT = 1;
